// Generated by CoffeeScript 1.7.1
(function() {
  describe("test", function() {
    return it("should return hello", function() {
      return expect(hello).toBe("Hello");
    });
  });

}).call(this);
